// 获取 DOM 对象
const connectBtn = document.getElementById("connect");
const disconnectBtn = document.getElementById("disconnect");
const sendBtn = document.getElementById("send");
const userName = document.getElementById("username");
const idDisplay = document.getElementById("peer-id-display");
const peerId = document.getElementById("peer-id");
const statusDom = document.getElementById("status");
const messageDOM = document.getElementById("messages");
const receivedMessagesDiv = document.getElementById("received-messages");
